### PR TITLE
Add compat to Project.toml

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by ararslan** [comment]
We should either add 0.7 to the compatible Julia versions or remove it from CI. I'd favor the latter, personally.

**Comment by giordano** [comment]
> I'd favor the latter, personally.

Me too

**Comment by ararslan** [comment]
Ugh, apparently the General auto-merging disagrees with our decision, since it was a patch release...

**Comment by giordano** [comment]
I thought the general registry wasn't supporting Julia v0.7 anymore, so that weren't effectively restricting anything

**Comment by ararslan** [comment]
I guess dropping 0.7 is still considered a version narrowing.

**Pull request merged**
